[package]
name = "mistralrs-quant"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
mcandle-core.workspace = true
mcandle-nn.workspace = true
half.workspace = true
serde.workspace = true
lazy_static = "1.4"
paste = "1.0.15"
tracing.workspace = true
rayon.workspace = true
byteorder = "1.5.0"
float8.workspace = true
once_cell.workspace = true
metal = { version = "0.27.0", features = ["mps"], optional = true }
thiserror = "1"

[features]
cuda = ["mcandle-core/cuda", "mcandle-nn/cuda", "dep:bindgen_cuda"]
metal = ["mcandle-core/metal", "mcandle-nn/metal", "dep:metal"]

[build-dependencies]
bindgen_cuda = { version = "0.1.5", optional = true }
