[workspace]
members = [
    "mistralrs-server",
    "mistralrs-core",
    "mistralrs-pyo3",
    "mistralrs",
    "mistralrs-bench",
    "mistralrs-vision",
    "mistralrs-quant",
    "mcandle/mcandle-core",
    "mcandle/mcandle-nn",
]
exclude = [
    "mistralrs-paged_attn",
    "mcandle/mcandle-flash-attn",
    "mcandle/mcandle-kernels",
    "mcandle/mcandle-metal-kernels",
]
resolver = "2"

[workspace.package]
version = "0.3.2"
edition = "2021"
description = "Fast and easy LLM serving."
homepage = "https://github.com/EricLBuehler/mistral.rs"
repository = "https://github.com/EricLBuehler/mistral.rs"
keywords = ["machine-learning"]
categories = ["science"]
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.80"
mcandle-core = { path = "./mcandle/mcandle-core", package = "mcandle-core" }
mcandle-flash-attn = { path = "./mcandle/mcandle-flash-attn" }
mcandle-kernels = { path = "./mcandle/mcandle-kernels" }
mcandle-metal-kernels = { path = "./mcandle/mcandle-metal-kernels" }
mcandle-nn = { path = "./mcandle/mcandle-nn" }
serde = "1.0.197"
serde_json = "1.0.114"
indexmap = { version = "2.2.5", features = ["serde"] }
either = { version = "1.10.0", features = ["serde"] }
accelerate-src = { version = "0.3.2" }
intel-mkl-src = { version = "0.8.1", features = ["mkl-static-lp64-iomp"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
futures = "0.3"
clap = { version = "4.5.1", features = ["derive", "wrap_help"] }
pyo3 = { version = "0.22.4", features = ["full", "extension-module", "either"] }
tokio = { version = "1.36.0", features = ["full", "rt-multi-thread"] }
once_cell = "1.19.0"
# All features but avif, avif increases the msrv dramatically
image = { version = "0.25.1", default-features = false, features = ['bmp', 'dds', 'exr', 'ff', 'gif', 'hdr', 'ico', 'jpeg', 'png', 'pnm', 'qoi', 'tga', 'tiff', 'webp']}
reqwest = { version = "0.12.4", features = ["blocking"] }
base64 = "0.22.1"
half = "2.4.0"
rayon = "1.1.0"
url = "2.5.2"
data-url = "0.3.1"
buildstructor = "0.5.4"
float8 = { version = "0.1.0", features = ["num-traits", "rand_distr"] }
regex = "1.10.6"
byteorder = "1.4.3"
cudarc = { version = "0.12.1", features = ["std", "cublas", "cublaslt", "curand", "driver", "nvrtc", "f16", "cuda-version-from-build-system", "dynamic-linking"], default-features=false }
gemm = { version = "0.17.0", features = ["wasm-simd128-enable"] }
libc = { version = "0.2.147" }
memmap2 = { version = "0.9.3", features = ["stable_deref_trait"] }
yoke = { version = "0.7.2", features = ["derive"] }
zip = { version = "1.1.1", default-features = false }
metal = { version = "0.27.0", features = ["mps"]}
num_cpus = "1.15.0"
num-traits = "0.2.15"
rand = "0.8.5"
rand_distr = "0.4.3"
safetensors = "0.4.1"
thiserror = "1"
ug = "0.0.2"
ug-cuda = "0.0.2"
ug-metal = "0.0.2"
criterion = { version = "0.5.1", default-features=false }
